### PR TITLE
Shashbuckle 4 and minor changes

### PR DESCRIPTION
**Pull request by MassimoC**
value controller deleted
valid uri for contact address
removed api version parameter in the route
move to swashbuckle 4 for easier control of operationId

### CODE REVIEW

**Comment by MassimoC** [comment]
OperationId
Before: World-cupV1PlayersGet 
Now: Players_GetPlayers

**Comment by MassimoC** [comment]
swagger: '2.0'
info:
  version: v1
  title: World Cup API
  description: World cup 2018 Russia
  termsOfService: N/A
  contact:
    name: API at Codit
    url: 'https://www.codit.eu'
    email: support@codit.eu
paths:
  /world-cup/v1/players:
    get:
      tags:
        - Players
      operationId: Players_GetPlayers
      consumes: []
      produces: []
      parameters:
        - name: top-players-only
          in: query
          required: false
          type: boolean
      responses:
        '200':
          description: Success
        '500':
          description: Server Error
    post:
      tags:
        - Players
      operationId: Players_Create
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: player
          in: body
          required: false
          schema:
            $ref: '#/definitions/Player'
      responses:
        '201':
          description: Success
        '500':
          description: Server Error
  '/world-cup/v1/players/{id}/vote':
    post:
      tags:
        - Players
      operationId: Players_VoteAsBestPlayer
      consumes: []
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '202':
          description: Success
        '404':
          description: Not Found
        '500':
          description: Server Error
  '/world-cup/v1/players/{id}':
    get:
      tags:
        - Players
      operationId: Players_GetPlayer
      consumes: []
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
        '404':
          description: Not Found
        '500':
          description: Server Error
    put:
      tags:
        - Players
      operationId: Players_UpdateFull
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
        - name: player
          in: body
          required: false
          schema:
            $ref: '#/definitions/PlayerDto'
      responses:
        '204':
          description: Success
        '404':
          description: Not Found
        '500':
          description: Server Error
    patch:
      tags:
        - Players
      operationId: Players_UpdateIncremental
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
        - name: player
          in: body
          required: false
          schema:
            $ref: '#/definitions/PlayerDto'
      responses:
        '204':
          description: Success
        '404':
          description: Not Found
        '500':
          description: Server Error
  '/world-cup/v1/players/{id}/update':
    patch:
      tags:
        - Players
      operationId: Players_UpdateIncrementalJsonPatch
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
        - name: player
          in: body
          required: false
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/Operation'
      responses:
        '204':
          description: Success
        '404':
          description: Not Found
        '500':
          description: Server Error
  /world-cup/v1/teams:
    get:
      tags:
        - Teams
      operationId: Teams_GetTeams
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
        '500':
          description: Server Error
  '/world-cup/v1/teams/{id}':
    get:
      tags:
        - Teams
      operationId: Teams_GetTeam
      consumes: []
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
        '404':
          description: Not Found
        '500':
          description: Server Error
definitions:
  Player:
    required:
      - firstName
    type: object
    properties:
      description:
        type: string
      firstName:
        type: string
      id:
        format: int32
        type: integer
      isTopPlayer:
        type: boolean
      team:
        $ref: '#/definitions/Team'
      teamId:
        format: int32
        type: integer
  Team:
    required:
      - name
    type: object
    properties:
      continent:
        enum:
          - Asia
          - Africa
          - NorthAmerica
          - SouthAmerica
          - Europe
          - Australia
        type: string
      description:
        type: string
      firstAppearence:
        format: int32
        type: integer
      id:
        format: int32
        type: integer
      name:
        type: string
      players:
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/Player'
      ranking:
        format: int32
        type: integer
      totalWins:
        format: int32
        type: integer
      updatedOn:
        format: date-time
        type: string
  PlayerDto:
    type: object
    properties:
      id:
        format: int32
        type: integer
      firstName:
        type: string
      description:
        type: string
      isTopPlayer:
        type: boolean
      teamId:
        format: int32
        type: integer
  Operation:
    type: object
    properties:
      value:
        type: object
      path:
        type: string
      op:
        type: string
      from:
        type: string

**Comment by MassimoC** [comment]
swagger will follow with link

**Comment by MassimoC** [comment]
https://acpcoditapiprogram.blob.core.windows.net/exchange/practical4.json

**Comment by tomkerkhove** [comment]
We might want to check our guidance on the operation name and align them. See our blog on why it's important

**Pull request merged**
