### PR TITLE
CI should build with release configuration

### PR DESCRIPTION
**Pull request by tomkerkhove**
CI should build with release configuration.

Relates to #108

### CODE REVIEW

**Comment by tomkerkhove** [comment]
We're not there yet but will tackle it next week, is that ok @fgheysels 	?

**Comment by fgheysels** [comment]
Created PR #124 that should fix the build.
Is there a possibility to run the build and tests before the PR can be closed / merged ?

**Comment by tomkerkhove** [comment]
@fgheysels 	Certainly there is, but the automatic trigger is broken for now. Working on that!

You can run `/azp run ci` which triggers it manually.

Sorry for the sloppy transition :(

**Comment by tomkerkhove** [comment]
That fixed it, thanks @fgheysels 	🎉

**Pull request merged**
